services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
