services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: ".env"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
