services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    environment:
      MP_DATABASE: /data/mailpit.db
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mailpit:/data

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: ".env"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file: ".env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: ".env"
    ports:
      - 8020:80
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  mailpit:
    driver: local
